image: python:3.11-slim
пеш 
stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python manage.py collectstatic --noinput

test:
  stage: test
  script:
    - python manage.py test

build:
  stage: build
  script:
    - echo "✅ Сборка завершена"